config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :reports

  # Defines the root path route ("/")
  # root "posts#index"
  resources :appointments
  resources :doctors
  get "/reports/:id/share", to: "reports#share", as: :share
  post "/reports/:id/email", to: "reports#email", as: :email

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.erb
<div class="footer">
    <%= link_to root_path do %>
    <i class="fa-solid fa-home" style="font-size: 24px; color: white;"></i>
  <% end %>
  <%= link_to reports_path do %>
    <i class="fa-solid fa-book" style="font-size: 24px; color: white;"></i>
  <% end %>
  <%= link_to appointments_path do %>
    <i class="fa-solid fa-calendar" style="font-size: 24px; color: white;"></i>
  <% end %>
  <%= link_to doctors_path do %>
    <i class="fa-solid fa-user-md" style="font-size: 24px; color: white;"></i>
  <% end %>
  <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
    <i class="fa-solid fa-sign-out" style="font-size: 24px; color: white;"></i>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex align-items-center border-bottom border-primary">
  <div class="container-fluid">

    <%= link_to root_path, class: "navbar-brand " do %>
       <h1 style="font-size: 35px ">HealthBook</h1>
    <% end %>
  </div>
</div>