config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :reports

  # Defines the root path route ("/")
  # root "posts#index"
  resources :appointments
  resources :doctors
  get "/reports/:id/share", to: "reports#share", as: :share
  post "/reports/:id/email", to: "reports#email", as: :email

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :user

  has_many :reports, dependent: :destroy
  has_many :appointments, dependent: :destroy

  validates :first_name, :last_name, :specialty, :email, presence: true

  validates :specialty, inclusion: { in: ["Internal Medicine", "Surgery", "Pediatrics", "Obstetrics and Gynecology", "Psychiatry", "Radiology", "Anesthesiology", "Emergency Medicine",
                                             "Pathology", "Ophthalmology", "Otolaryngology (ENT)", "Dermatology", "Neurology",
                                            "Urology", "Orthopedics", "Physical Medicine and Rehabilitation", "Allergy and Immunology",
                                             "Infectious Diseases", "Endocrinology", "Cardiology"]
                                    }
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = current_user.doctors.all
  end

  def new
    @doctor = Doctor.new
  end


  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.user = current_user
    @doctor.save

    if @doctor.save
      redirect_to doctors_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

    @doctor = current_user.doctors.find(params[:id])
  end

  def update
    @doctor = current_user.doctors.find(params[:id])
    if @doctor.update(doctor_params)
      redirect_to doctors_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @doctor = current_user.doctors.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path, status: :see_other
  end


  private

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :specialty, :email)
  end

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end
end

app/views/doctors/_form.html.erb
<div class='main'>
  <%= simple_form_for @doctor, html: { autocomplete: 'off' } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :first_name, input_html: { class: "bg-white" } %>
    <%= f.input :last_name, input_html: { class: "bg-white" } %>
    <%= f.input :email, input_html: { class: "bg-white" } %>
    <%= f.input :specialty, collection: ["Internal Medicine", "Surgery", "Pediatrics", "Obstetrics and Gynecology",
                                         "Psychiatry", "Radiology", "Anesthesiology", "Emergency Medicine",
                                         "Pathology", "Ophthalmology", "Otolaryngology (ENT)", "Dermatology", "Neurology",
                                         "Urology", "Orthopedics", "Physical Medicine and Rehabilitation", "Allergy and Immunology",
                                         "Infectious Diseases", "Endocrinology", "Cardiology"],
                             input_html: { class: "bg-white" } %>
    <%= f.submit "Add doctor", class: "btn btn-primary form-submit-btn" %>
  <% end %>
</div>

app/views/doctors/edit.html.erb
<div class='main'>
  <h3 style="text-align: center; mb-3;">Edit doctor</h3>
  <%= link_to doctors_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
</div>

<%= render "form", report: @doctor %>

app/views/doctors/index.html.erb
<div class="main">
  <div class="d-flex align-items-center mt-3">
    <%= link_to root_path do %>
      <i class="fa-solid fa-arrow-left ms-3 back-arrow"></i>
    <% end %>
    <div class="mx-auto text-center">
      <h2>Your Doctors</h2>
    </div>
      <div class="d-flex justify-content-end">
        <%= link_to new_doctor_path do %>
          <i class="fa-solid fa-plus text-primary mb-1 btn bg-primary text-white"></i>
        <% end %>
    </div>
  </div>



  <div class="doctor-cards">
    <% @doctors.each do |doctor| %>
      <div class="doctor card">
        <div class="avatar-doctor bg-secondary rounded-circle d-flex justify-content-center align-items-center">
          <%= doctor.first_name[0] + doctor.last_name[0] %>
        </div>

        <div class="doctor-info d-flex justify-content-end">
          <div>
            <h3 class="doctor-card-title"><%= doctor.first_name + " " + doctor.last_name %></h3>
            <p class="doctor-card-text"><%= doctor.specialty %></p>

          </div>

          <div class="doctor-icons mt-0 ml-auto">
            <%= link_to edit_doctor_path(doctor) do %>
              <i class="fa-regular fa-pen-to-square me-1"></i>
            <% end %>
            <%= link_to doctor_path(doctor), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"} do %>
              <i class="fa-regular fa-trash-can"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/doctors/new.html.erb
<div class='main'>
  <div class="d-flex align-items-center mt-3">
    <%= link_to doctors_path do %>
      <i class="fa-solid fa-arrow-left ms-3 back-arrow"></i>
    <% end %>
    <div class="mx-auto text-center">
      <h2>New Doctor</h2>
    </div>
  </div>

  <%= simple_form_for @doctor, html: { autocomplete: 'off' } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :first_name, label: false, input_html: { class: "bg-white" }, placeholder: "First name*"%>
    <%= f.input :last_name, label: false, input_html: { class: "bg-white" }, placeholder: "Last name*"%>
    <%= f.input :email, label: false, input_html: { class: "bg-white" }, placeholder: "Email*"  %>
    <%= f.input :specialty, label: false, collection: ["Internal Medicine", "Surgery", "Pediatrics" ,"Obstetrics and Gynecology", "Psychiatry", "Radiology", "Anesthesiology", "Emergency Medicine","Pathology", "Ophthalmology", "Otolaryngology (ENT)" , "Dermatology", "Neurology", "Urology", "Orthopedics" , "Physical Medicine and Rehabilitation", "Allergy and Immunology", "Infectious Diseases", "Endocrinology", "Cardiology"], input_html: { class: "bg-white" }, include_blank: "Specialty*" %>
    <%= f.submit "Create Doctor", class: "btn btn-primary form-submit-btn" %>
  <% end %>
</div>