config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :reports

  # Defines the root path route ("/")
  # root "posts#index"
  resources :appointments
  resources :doctors
  get "/reports/:id/share", to: "reports#share", as: :share
  post "/reports/:id/email", to: "reports#email", as: :email

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  accepts_nested_attributes_for :doctor
  validates_associated :doctor
  has_many :appointment_attachements, dependent: :destroy
  has_many :reports, through: :appointment_attachements
  validates :appointment_date, presence: true

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
    @appointment = Appointment.new
    @appointment.build_doctor
    @doctors = Doctor.all
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @doctor = Doctor.new(appointment_params[:doctor_attributes])
    @doctor.user = current_user
    @doctor.save
    @appointment.doctor = @doctor

   @report_ids = params[:appointment][:report_ids]

   @report_ids.each_with_index do |report_id, index|
    next if index == 0
    @appointment.reports << Report.find(report_id)
    # @appointment_attachements.reports << Report.find(report_id)

   end



   @appointment.save


    if @appointment.save
      redirect_to appointments_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @appointment = current_user.appointments.find(params[:id])
    @doctors = Doctor.all
  end

  def update
    @appointment = current_user.appointments.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to appointments_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @appointments = current_user.appointments
  end

  def destroy
    @appointment = current_user.appointments.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path, status: :see_other
  end


  private

  def appointment_params
    params.require(:appointment).permit(:appointment_date, :time, :doctor_id, report_ids: [], doctor_attributes: [:email, :first_name, :last_name, :specialty])
  end

  def set_appointment
    @appointment = current_user.appointments.find(params[:id])
  end

end

app/views/appointments/_appointment_card.html.erb
<li class="appointment-card">
  <div class="appointment-date">
    <div>
      <%= appointment.appointment_date.day %>
    </div>
    <div>
      <%= appointment.appointment_date.strftime("%B").first(3) %>
    </div>
  </div>

  <div class="appointment-details">
    <div class="appointment-head">
      <div class="appointment-title">
        <p class="mb-0 mt-0" style="color: #176B87">Dr. <%= appointment.doctor.first_name + " " + appointment.doctor.last_name %></p>
      </div>
      <div class="appointment-specialty">
        <%= appointment.doctor.specialty %>
      </div>
    </div>
      <div style="color: gray; text-align: left; font-size: 16px;"><%= "#{appointment.time.strftime("%I:%M %p")}" %></div>
    <% if appointment.reports.present? %>
      <p class="mt-0" style="color: #176B87; text-align: left;"> <%# appointments.each do |appointment| %>
        <% appointment.reports.each_with_index do |report, index| %>
          <% next if index == 0 %>
          <i class="fa-solid fa-paperclip"></i>
            <%= link_to report.title, report_path(report) %>
          <% end %>
      <%# end %>
      <% end %>
      </p>


  </div>

</li>

app/views/appointments/_appointment_swiper.html.erb
<%# swiper start %>
<div class="swiper-container" data-controller="swiper">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <%# all the content of the appointment card%>
      <div class="adjusted-appointment_card" style="width:90%;">
        <%= render "appointment_card", appointment: appointment%>
      </div>
      <%# end of all the content of the appointment card%>
    </div>
    <div class="swiper-slide">
      <div class="appointment-card p-3 appointment-card-buttons">
        <%= link_to edit_appointment_path(appointment) do %>
          <i class="fa-solid fa-pen-to-square  text-align-center"></i>
        <% end %>
        <%= link_to appointment_path(appointment), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"} do %>
          <i class="fa-regular fa-trash-can ms-1 text-align-center"></i>
        <% end %>
      </div>
    </div>

  </div>
  <!-- Pagination -->
  <!-- Navigation -->
</div>
<%# swiper end %>

app/views/appointments/_form.html.erb
<div class='main'>
  <%= simple_form_for [appointment] do |f| %>
  <%= f.input :appointment_date,
              as: :string,
              label: false,
              input_html: { data: { controller: "datepicker" }, class: "bg-white", placeholder: "Appointment date"}
               %>

<%= f.input :time,
              as: :time, label: false, input_html: { class: "bg-white" }%>
 <%# <%= f.association :reports, label: false, collection: current_user.reports.all.map { |report| ["#{report.title}", report.id] }, include_blank: "Select Report" %> 
  <%# <%= f.association :doctor, label: "Doctor", collection: Doctor.all, label_method: :name, value_method: :id, include_blank: "Select Doctor" %>
  <%= f.association :doctor, label: false, collection: Doctor.all.map { |doctor| ["#{doctor.first_name} #{doctor.last_name}", doctor.id] }, include_blank: "Select Doctor", input_html: { class: "bg-white" },include_blank: "Select Doctor*" %>

  <%= f.button :submit , class: "btn btn-primary form-submit-btn"%>
  <% end %>
</div>

app/views/appointments/edit.html.erb
<div class='main'>
  <h3 style="text-align: center; mb-3;">Edit appointment</h3>
  <%= link_to appointments_path do %>
    <i class="fa-solid fa-arrow-left ms-3 back-arrow"></i>
  <% end %>
</div>

<%= render "form", appointment: @appointment %>

app/views/appointments/index.html.erb
<div class="sticky-head">
  <div class="d-flex align-items-center mt-1">
    <%= link_to root_path do %>
      <i class="fa-solid fa-arrow-left ms-3 back-arrow" ></i>
    <% end %>
    <div class="mx-auto text-center">
      <h2 style="color: #176B87;">Appointments</h2>
    </div>
    <div class="add-button-div">
      <%= link_to new_appointment_path do %>
        <i class="fa-solid fa-plus  text-primary mb-1 btn bg-primary text-white"></i>
      <% end %>
  </div>
  </div>


</div>

<div class="main">


<ul class="appointments">
  <h5>Upcoming</h5>
  <% @appointments.sort_by(&:appointment_date).each do |appointment| %>
    <% if appointment.appointment_date > Date.today %>
      <%= render "appointment_swiper", appointment: appointment %>
    <% end %>
  <% end %>

  <h5>Past</h5>
  <% @appointments.sort_by(&:appointment_date).reverse_each do |appointment| %>
    <% if appointment.appointment_date <= Date.today %>

      <%= render "appointment_swiper", appointment: appointment %>
    <% end %>
  <% end %>
</ul>

</div>

app/views/appointments/new.html.erb
<div class='main' data-controller="show-doctors">
 <div class="d-flex align-items-center mt-3">
    <%= link_to appointments_path do %>
      <i class="fa-solid fa-arrow-left ms-3"></i>
    <% end %>
    <div class="mx-auto text-center">
      <h2>New Appointment</h2>
    </div>
  </div>

  <%= simple_form_for [@appointment] do |f| %>
  <%= f.input :appointment_date,
            as: :string,
            label: false,
            input_html: { data: { controller: "datepicker" } },
            class: "bg-light", placeholder: "Appointment date*"%>
  <%= f.input :time,
            as: :time,
            label: false,
            input_html: { class: "bg-white" } %>

  <%= f.association :reports, label: false, collection: current_user.reports.all.map { |report| ["#{report.title}", report.id] }, include_blank: "Select Report" %>
  <%#= f.input :report_ids, collection: @reports %>
  <div class="doctors-button-container">
    <button type="button" class="btn-select-doctors btn-select-doctors-active" data-action="click->show-doctors#showselect" data-show-doctors-target="selectbutton">Select doctor</button>
    <button type="button" class="btn-select-doctors" data-action="click->show-doctors#showquestions" data-show-doctors-target="questionsbutton">Add doctor</button>
  </div>
  <div data-show-doctors-target="select">
    <%#
    <%= f.association :doctor, label: "Doctor", collection: Doctor.all, label_method: :first_name, value_method: :id, include_blank: "Select Doctor" %>
    <%= f.association :doctor, label: false, collection: current_user.doctors.all.map { |doctor| ["#{doctor.first_name} #{doctor.last_name}", doctor.id] }, include_blank: "Select Doctor*" %>
  </div>




  <div data-show-doctors-target="questions" class="hidden">
  <%= f.simple_fields_for :doctor do |d| %>
        <%= d.input :first_name, label: false, input_html: { class: "bg-white" }, placeholder: "First name*" %>
        <%= d.input :last_name, label: false, input_html: { class: "bg-white" }, placeholder: "Last name*" %>
        <%= d.input :email, label: false, input_html: { class: "bg-white" }, placeholder: "Email*"%>
        <%= d.input :specialty, label: false, collection: ["Internal Medicine", "Surgery", "Pediatrics", "Obstetrics and Gynecology", "Psychiatry", "Radiology", "Anesthesiology", "Emergency Medicine", "Pathology", "Ophthalmology", "Otolaryngology (ENT)", "Dermatology", "Neurology", "Urology", "Orthopedics", "Physical Medicine and Rehabilitation", "Allergy and Immunology", "Infectious Diseases", "Endocrinology", "Cardiology"], input_html: { class: "bg-white" }, include_blank: "Specialty*"%>
      <% end %>
</div>

  <%= f.submit "Create Appointment", class: 'btn btn-primary form-submit-btn' %>

  <% end %>
</div>