config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :reports

  # Defines the root path route ("/")
  # root "posts#index"
  resources :appointments
  resources :doctors
  get "/reports/:id/share", to: "reports#share", as: :share
  post "/reports/:id/email", to: "reports#email", as: :email

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :doctor, optional: true
  accepts_nested_attributes_for :doctor
  validates_associated :doctor


  has_many :appointment_attachements, dependent: :destroy
  has_many :appointments, through: :appointment_attachements


  validates :title, :report_date, :category, presence: true

  validates :category, inclusion: { in: ['Blood Tests', 'Imaging', 'Surgery', 'Pathology', 'Cardiology', 'Endoscopy', 'Pulmonary Function Test (PFT)', 'Genetic Testing', 'Allergy Testing', 'Neurological', 'Dermatology', 'Obstetric and Gynecological', 'Urology', 'Orthopedic', 'Gastroenterology', 'Ophthalmology', 'Nuclear Medicine', 'Psychiatric', 'Rehabilitation', 'Dental'] }

  include PgSearch::Model
  pg_search_scope :search_by_title_and_note, against: [:title, :note], using: { tsearch: { prefix: true } }

  has_one_attached :photo
  has_one_attached :pdf
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  require 'rqrcode'
  def index
    if params[:query].present?
      @reports = current_user.reports.order(report_date: :desc).search_by_title_and_note(params[:query])
    elsif params[:category].present?
      @reports = current_user.reports.order(report_date: :desc).where(category: params[:category])
    elsif params[:report_date].present?
      @reports = current_user.reports.order(report_date: :desc).where(report_date: params[:report_date])

    else
      @reports = current_user.reports.all.order(report_date: :desc)
    end

    @categories = Report.pluck(:category).uniq
  end

  def show
    @report = current_user.reports.find(params[:id])
    @report.viewed_at = Time.now
    @report.save

    @link_for_qr_code = "www.thehealthbook.online/reports/#{@report.id}"
    @qr_code = RQRCode::QRCode.new(@link_for_qr_code)
    @svg = @qr_code.as_svg(
      offset: 0,
      fill: 'white',
      color: '64CCC5',
      shape_rendering: 'crispEdges',
      standalone: true,
      module_size: 4
    )
  end

  def new
    @report = Report.new
    @report.build_doctor
  end

  def create
    @report = Report.new(report_params)
    @doctor = Doctor.new(report_params[:doctor_attributes])
    @doctor.user = current_user
    @doctor.save
    @report.user = current_user
    @report.doctor = @doctor
    if params[:report][:doctor_id].present?
      @report.doctor = Doctor.find(params[:report][:doctor_id])
    end

    @report.viewed_at = Time.now

    if params[:report][:photo].present?
      to_be_formatted = convert_image_to_content
      @report.save
      NewReportJob.perform_later(@report.id, to_be_formatted)
      flash[:notice] = "Your report is being updated"

      # @report.note = format_content(to_be_formatted)
    elsif params[:report][:pdf].present?
      @report.note = convert_pdf_to_text
    end

    if @report.save
      redirect_to reports_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @report = current_user.reports.find(params[:id])
  end

  def update
    @report = current_user.reports.find(params[:id])
    @report.update(report_params)
    @report.viewed_at = Time.now
    redirect_to report_path(@report)
  end

  def destroy
    @report = current_user.reports.find(params[:id])
    @report.destroy
    redirect_to reports_path, status: :see_other
  end

  def share
    @report = current_user.reports.find(params[:id])
    @doctors = Doctor.all
    recipient_email = params[:report][:doctor_email]
    @link_for_qr_code = "www.thehealthbook.online/reports/#{@report.id}"
    @qr_code = RQRCode::QRCode.new(@link_for_qr_code)
    @svg = @qr_code.as_svg(
      offset: 1,
      color: white,
      shape_rendering: 'crispEdges',
      standalone: true,
      module_size: 4
    )
  end

  def email
    @report = Report.find(params[:id])
    @recipient_email = params[:doctor_email]
    HealthMailer.share_report(@report, @recipient_email).deliver_now

   redirect_to report_path(@report)
  end

  private

  require 'net/http'

  def report_params
    params.require(:report).permit(:title, :category, :note, :current_user_id, :report_date, :photo, :qr_code, :doctor_id, :doctor_first_name, :doctor_last_name, doctor_attributes: [:email, :first_name, :last_name, :specialty])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :specialty, :email)
  end
  def convert_image_to_content
    # image_url = Cloudinary::Utils.cloudinary_url(@report.photo)
    begin
      # uri = URI.parse(image_url)
      # response = Net::HTTP.get_response(uri)
      # tempfile = Tempfile.new(['image', '.png']).set_encoding('ASCII-8BIT')
      # tempfile.write(response.body)
      # RTesseract.new(tempfile.path).to_s
      uploaded_file = params[:report][:photo]
      result = RTesseract.new(uploaded_file.path).to_s
    end
  end

  def convert_pdf_to_text
    pdf_io = params[:report][:pdf].tempfile
    result = PDF::Reader.new(pdf_io).pages.first.text
  end

  def format_content(to_be_formatted)
    client = OpenAI::Client.new
    chaptgpt_response = client.chat(parameters: {
      model: "gpt-3.5-turbo",
      messages: [{ role: "user", content: "Format the report content for it to be displayed in a nice format. Make sure it is HTML formatted as it will be displayed in an html.erb file: #{to_be_formatted}. Give me only your formatted output, without any of your own comments"}]
      })
    chaptgpt_response["choices"][0]["message"]["content"]
  end
end

app/views/reports/_form.html.erb
<div data-controller="show-doctors">
  <%= simple_form_for report, html: { autocomplete: 'off', data: {controller: "photo-preview pdf-preview"} } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


    <%= f.input :title, label: false, input_html: {class: "bg-white"}, placeholder: "Title*"%>
    <%= f.input :report_date,
                as: :string, label: false,
                input_html: { data: { controller: "datepicker" }, class: "bg-white"}, placeholder: "Date"
                %>
    <%# Should do mapping in controller %>


    <%= f.input :category, label: false, collection: ['Blood Tests', 'Imaging', 'Surgery', 'Pathology', 'Cardiology', 'Endoscopy', 'Pulmonary Function Test (PFT)', 'Genetic Testing', 'Allergy Testing', 'Neurological', 'Dermatology', 'Obstetric and Gynecological', 'Urology', 'Orthopedic', 'Gastroenterology', 'Ophthalmology', 'Nuclear Medicine', 'Psychiatric', 'Rehabilitation', 'Dental'], input_html: {class: "bg-white"}, include_blank: "Category*"%>


    <% if params[:choice] == "photo" %>

    <%= f.input :photo, as: :file, input_html: { class: 'd-none', data: { photo_preview_target: "input", action:"change->photo-preview#displayPreview" }}, label_html: { class: 'upload-photo btn btn-upload'}, label: '📷 Photo'%>
      <%= image_tag "", width: 300, class: "hidden", data: { photo_preview_target: "preview" } %>
    <% elsif params[:choice] == "pdf" %>
      <%= f.input :pdf, as: :file, input_html: { class: 'd-none', data: { pdf_preview_target: "input", action:"change->pdf-preview#displayPreview" }}, label_html: { class: 'upload-pdf btn btn-upload'}, label: '📷 PDF'%>
       <iframe type="application/pdf" width="300" class="hidden" data-pdf-preview-target="preview"></iframe>
    <% elsif params[:choice] == "manual"%>
      <%= f.input :note, label: false, input_html: {class: "bg-white"}, placeholder: "Note"%>
    <% end %>




    <div class="doctors-button-container">
      <button type="button" class="btn-select-doctors btn-select-doctors-active" data-action="click->show-doctors#showselect" data-show-doctors-target="selectbutton">Choose doctor</button>
      <button type="button" class="btn-select-doctors" data-action="click->show-doctors#showquestions" data-show-doctors-target="questionsbutton">Add doctor</button>
    </div>

    <div data-show-doctors-target="select">
      <%= f.association :doctor, label: false, collection: current_user.doctors.all.map { |doctor| ["#{doctor.first_name} #{doctor.last_name}", doctor.id] }, include_blank: "Select Doctor*", input_html: {class: "bg-white"}%>
    </div>
    <div id="additional-doctor-fields" data-show-doctors-target="questions" class="hidden">
       <%= f.simple_fields_for :doctor do |d| %>
        <%= d.input :first_name, label: false, input_html: { class: "bg-white" }, placeholder: "First name*" %>
        <%= d.input :last_name, label: false, input_html: { class: "bg-white" }, placeholder: "Last name*" %>
        <%= d.input :email, label: false, input_html: { class: "bg-white" }, placeholder: "Email*"%>
        <%= d.input :specialty, label: false, collection: ["Internal Medicine", "Surgery", "Pediatrics", "Obstetrics and Gynecology", "Psychiatry", "Radiology", "Anesthesiology", "Emergency Medicine", "Pathology", "Ophthalmology", "Otolaryngology (ENT)", "Dermatology", "Neurology", "Urology", "Orthopedics", "Physical Medicine and Rehabilitation", "Allergy and Immunology", "Infectious Diseases", "Endocrinology", "Cardiology"], input_html: { class: "bg-white" }, include_blank: "Specialty*"%>
      <% end %>
    </div>
    <%= f.submit class: "btn btn-primary form-submit-btn" %>
  <% end %>
</div>

app/views/reports/_icon.html.erb
   <div class="report-icon">
      <% if report.category == "Blood Tests" %>
        <i class="fa-solid fa-droplet"></i>
      <% elsif (report.category == "Imaging" || report.category == "Surgery") %>
        <i class="fa-solid fa-hospital"></i>
      <% elsif report.category == 'Cardiology' %>
        <i class="fa-solid fa-heart-pulse"></i>
      <% elsif report.category == 'Pulmonary Function Test (PFT)' %>
        <i class="fa-solid fa-lungs"></i>
      <% elsif report.category == 'Genetic Testing' %>
        <i class="fa-solid fa-dna"></i>
      <% elsif report.category == 'Neurological' %>
        <i class="fa-solid fa-brain"></i>
      <% elsif (report.category == 'Obstetric and Gynecological' || report.category == "Urology" || report.category == "Dermatology" || report.category == "Gastroenterology" || report.category == 'Endoscopy') %>
        <i class="fa-solid fa-stethoscope"></i>
      <% elsif report.category == 'Orthopedic' %>
        <i class="fa-solid fa-bone"></i>
      <% elsif report.category == 'Ophthalmology' %>
        <i class="fa-solid fa-eye"></i>
      <% elsif report.category == 'Dental' %>
        <i class="fa-solid fa-tooth"></i>
      <% elsif (report.category == 'Allergy Testing' || report.category == 'Nuclear Medicine') %>
        <i class="fa-solid fa-vial-virus"></i>
      <% elsif report.category == 'Pathology' %>
        <i class="fa-solid fa-virus"></i>
      <% elsif %>
        <i class="fa-solid fa-user-doctor"></i>
      <% end %>
    </div>

app/views/reports/_icon_cat.html.erb
      <% if category == "Blood Tests" %>
        <i class="fa-solid fa-droplet"></i>
      <% elsif (category == "Imaging" || category == "Surgery") %>
        <i class="fa-solid fa-hospital"></i>
      <% elsif category == 'Cardiology' %>
        <i class="fa-solid fa-heart-pulse"></i>
      <% elsif category == 'Pulmonary Function Test (PFT)' %>
        <i class="fa-solid fa-lungs"></i>
      <% elsif category == 'Genetic Testing' %>
        <i class="fa-solid fa-dna"></i>
      <% elsif category == 'Neurological' %>
        <i class="fa-solid fa-brain"></i>
      <% elsif (category == 'Obstetric and Gynecological' || category == "Urology" || category == "Dermatology" || category == "Gastroenterology" || category == 'Endoscopy') %>
        <i class="fa-solid fa-stethoscope"></i>
      <% elsif category == 'Orthopedic' %>
        <i class="fa-solid fa-bone"></i>
      <% elsif category == 'Ophthalmology' %>
        <i class="fa-solid fa-eye"></i>
      <% elsif category == 'Dental' %>
        <i class="fa-solid fa-tooth"></i>
      <% elsif (category == 'Allergy Testing' || category == 'Nuclear Medicine') %>
        <i class="fa-solid fa-vial-virus"></i>
      <% elsif category == 'Pathology' %>
        <i class="fa-solid fa-virus"></i>
      <% elsif %>
        <i class="fa-solid fa-user-doctor"></i>
      <% end %>

app/views/reports/_report_card.html.erb
<%= link_to report_path(report), class: 'card-link text-decoration-none' do %>
 <li class="report-card">

    <%= render "reports/icon", report: report %>

    <div class="report-details">
      <div class="report-head">
        <div class="report-title ">
          <p class="mb-0 mt-0"><%#= link_to report.title, report_path(report), class: "text-decoration-none" %><%= report.title %></p>
        </div>
        <div class="report-category">
          <%= report.category %>
        </div>
      </div>
     <div class="report-content">
        <% if report.note.present? %>
          <%= strip_tags(report.note.sub(/.*?<body[^>]*>/im, '')) %>
        <% else %>
          <div class="d-flex align-items-between">
            <div class="spinner-border spinner-border-sm ml-auto me-2" role="status" aria-hidden="true"></div>
            <strong>Loading...</strong>
          </div>
        <% end %>
      </div>
      <div class="report-edit">
        <%= report.report_date.day %> <%= (Date::MONTHNAMES[report.report_date.month]).first(3) %>
      </div>
    </div>

  </li>
<% end %>

app/views/reports/edit.html.erb
<div>
  <%= link_to report_path(@report) do %>
    <i class="fa-solid fa-arrow-left ms-3 back-arrow"></i>
  <% end %>
  <h3>Edit report</h3>
</div>

<%= render "form", report: @report %>

app/views/reports/index.html.erb
<div class="sticky-head">
  <div class="d-flex align-items-center">
    <%= link_to root_path do %>
      <i class="fa-solid fa-arrow-left ms-3 back-arrow" ></i>
    <% end %>
    <div class="mx-auto text-center">
      <h2 style="color: #176B87;">Medical reports</h2>
    </div>
      <div class="add-button-div" data-controller="report-type">
        <div class="dropdown">
          <!-- Button trigger dropdown -->
          <i class="fa-solid fa-plus  text-primary mb-1 btn bg-primary text-white" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"></i>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><%= link_to "Upload image", new_report_path(choice: 'photo'), class: "dropdown-item", data: { action: "click->report-type#selectOption", choice: "photo" } %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Upload pdf", new_report_path(choice: 'pdf'), class: "dropdown-item", data: { action: "click->report-type#selectOption", choice: "pdf" } %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Fill manually", new_report_path(choice: 'manual'), class: "dropdown-item", data: { action: "click->report-type#selectOption", choice: "manual" } %></li>
          </ul>
        </div>
      </div>
  </div>


    <div class="searchbar">
      <%= form_with url: reports_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control p-0 ps-1 radius-4",
              placeholder: "Find a report"

          %>
        <%= text_field_tag :report_date,
            params[:report_date],
            data: { controller: "datepicker"}, class: "form-control p-0 ps-1 ms-1 radius-4", placeholder: "Pick a date" %>

        <%= submit_tag "Search", name: "", class: "btn bg-primary m-0 p-0 ms-1 p-1 radius-4", style: "color: white;" do %>
         <% end %>
        <% end %>
    </div>

  <div class="scrolling-wrapper">
    <ul class="inline-list">
      <%= link_to reports_path, class:"text-decoration-none" do %>
        <div class="all-button", style= "background-color: #9e0059; color: white;">
          <p class="mt-0"><strong>All</strong></p>
        </div>
      <% end %>
      <% @categories.each do |category|%>
          <li>
            <%= link_to reports_path(category: category ), class: "text-decoration-none" do %>
            <div  class="all-button">
              <div class="d-flex align-items-center">
                <%= render "icon_cat", category: category %>
                <p class="ms-2 mt-0"><%= category %></p>
              </div>
            </div>
            <% end %>
          </li>
        <% end %>
    </ul>
  </div>
</div>

<div class="main">
  <ul class="reports">
    <% @reports.each do |report|%>
      <% if report.user == current_user%>
        <%= render "report_card", report: report %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/reports/new.html.erb
<div class="sticky-head">
  <div class="d-flex align-items-center mt-1">
    <%= link_to reports_path do %>
      <i class="fa-solid fa-arrow-left ms-3 back-arrow"></i>
    <% end %>
    <div class="mx-auto text-center">
      <h3>New report</h3>
    </div>
  </div>
</div>

<div class="main">
  <%= render "form", report: @report %>
</div>

app/views/reports/show.html.erb
<div class="sticky-head">
  <div class="d-flex align-items-center">
    <%= link_to reports_path do %>
      <i class="fa-solid fa-arrow-left ms-3 back-arrow" ></i>
    <% end %>
    <div class="mx-auto text-center">
      <h2><%= @report.title %></h2>
    </div>
  </div>

  <div class="d-flex justify-content-end my-2">
    <%= link_to edit_report_path(@report) do %>
      <i class="fa-solid fa-pen-to-square me-3 btn bg-primary text-white"></i>
    <% end %>
      <%= link_to "", "data-bs-toggle": "modal", "data-bs-target": "#exampleModal" do %>
        <i class="fa-solid fa-share me-3 btn bg-primary text-white"></i>
    <% end %>
    <%= link_to report_path(@report), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fa-regular fa-trash-can btn bg-primary text-white"></i>
    <% end %>
  </div>




  <%# start card for the report %>
  <div class="one-report-card">
    <div class="one-report-details">
      <% if @report.doctor.present? %>
        <div class="d-flex align-items-center justify-content-between">
          <p class= "mb-1"style="font-size: 16px;"><strong><%=@report.doctor.first_name + " " + @report.doctor.last_name%></strong></p>
          <p  class= "ms-2 mb-1" style="font-size: 16px;"> | </p>
          <p class= "ms-2 mb-1" style="font-size: 16px; color: #9E0059"> <%= @report.doctor.specialty %></p>
        </div>

        <div class="d-flex">
          <%= @report.report_date.strftime("%A") %>
          <%= @report.report_date.day %>
          <%= (Date::MONTHNAMES[@report.report_date.month]) %>
        </div>

      <% else %>
        <h4>No doctor selected</h4>
        <div class="d-flex">
          <%= @report.report_date.day %>
          <%= (Date::MONTHNAMES[@report.report_date.month]) %>
        </div>
      <% end %>
    </div>
  </div>

</div>


<div class="main">
  <div class="one-report-content mt-3">
    <%= @report.note.html_safe %>
  </div>

  <div class="one-report-documents mt-3">
    <h3>Original documents</h3>
    <% if @report.photo.present? %>
      <div class="report-image mt-3">

        <%= link_to "", "data-bs-toggle": "modal", "data-bs-target": "#imageModal" do %>
           <%= cl_image_tag(@report.photo.key , height: 180, width: 120, crop: :fill) %>
         <% end %>
      </div>
    <% else %>
      <%= "You don't have any document attached." %>
    <% end %>
  </div>
</div>


    <!-- Button trigger modal -->
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body m-3 border-bottom">
            <div>
              <h2>Share <%= @report.title %></h2>
              <h3>by QR Code</h3>
              <div class="qr_code">
                <%= @svg.html_safe %>
              </div>
            </div>
          </div>
          <div>
            <h3>by E-mail</h3>
            <div class="email m-3" style="text-align: center;">
              <%= form_with url: email_path(@report), method: :post, html: { style: "display: flex; justify-content: center; align-items: center;" } do |f| %>
                <%= f.select :doctor_email, current_user.doctors.all.map { |doctor| ["#{doctor.first_name} #{doctor.last_name} (#{doctor.email})", doctor.email] }, { include_blank: "Select Doctor" }, { style: 'width: 50%' } %>
                <%= f.submit "Share", :onclick => "return confirm('#{@report.title } has been shared')",  class: "btn bg-primary m-0 p-0 ms-1 p-1", style:"color:white;", :confirm => 'Are you sure?' %>


              <% end %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>


    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <% if @report.photo.present? %>
            <%= cl_image_tag(@report.photo.key, class: "img-fluid") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>